### ISSUE TITLE
Unable to load any jxr 5120x1440 HDR screenshots

### ISSUE THREAD

**Issue by Filoppi** [13thsymphony/HDRImageViewer#47]
[Red Dead Redemption 2 18_01_2022 02_02_14.zip](https://github.com/13thsymphony/HDRImageViewer/files/7989701/Red.Dead.Redemption.2.18_01_2022.02_02_14.zip)

I just get the message: "Unable to load this image" "The image file may be corrupted or invalid.".
I attached a sample screenshot. I take these screenshots through the xbox game bar/app, and if I change the resolution to 4k on my other monitor, the screenshots can be opened just fine. It's possible the issue is in the way the screenshot is saved, and not in your app, but I have no reason to believe that.

I was trying to debug and fix the issue myself but I'm unable to build yet, as the instructions are not clear to me (and I have no time to delve into it atm): if this is merged https://github.com/13thsymphony/HDRImageViewer/pull/46 I could still look into the issue myself.

**Comment by Kaldaien** [comment]
This happens at more or less any resolution with dimensions > 4096.

**Comment by imbushuo** [comment]
@Filoppi I proposed a fix in https://github.com/13thsymphony/HDRImageViewer/pull/49, seems fixed the issue

**Comment by Filoppi** [comment]
Pretty sure we are having the same base issue, so it should fix it, though my DPI is 100% so maybe not.
Download the screenshot I attached and try.

Could you tell me how you got through the issue that I mention here:
https://github.com/13thsymphony/HDRImageViewer/pull/46
because I can't build (nor test) otherwise.

**Comment by imbushuo** [comment]
@Filoppi I applied a similar patch, though it's not FI-ed with the same PR. The screenshot you sent works, so I believe this should be mitigated.

**Comment by Filoppi** [comment]
@imbushuo Well, let's just hope the Author accepts the PR. If you think it's a Direct2D bug, you could also report it to MS.

**Comment by ValZapod** [comment]
Fixed, can be closed.

**Comment by Filoppi** [comment]
> Fixed, can be closed.

Fixed how? By what commit?

**Comment by ValZapod** [comment]
> > Fixed, can be closed.
> 
> Fixed how? By what commit?

Latest app from Store does not have this problem. It may be a windows 11 fix.

**Comment by Filoppi** [comment]
> > > Fixed, can be closed.
> > 
> > 
> > Fixed how? By what commit?
> 
> Latest app from Store does not have this problem. It may be a windows 11 fix.

I just tried again, I'm on the latest Windows 11 build and I have updated all my store apps, the `HDR + WCG Image Viewer` app hasn't been updated for months, and the issue is still present. Nothing changed.

**Comment by ValZapod** [comment]
Oh, so this does not happen on 4K resolution. Understood. Not fixed then.

**Comment by Sawtaytoes** [comment]
Just loaded this on my 3840x1600 monitor at 100%:
![image](https://user-images.githubusercontent.com/3948069/192970825-ab28799f-b6ff-447b-86be-9d14f285cba5.png)

Is it that you need to be on a larger screen for it to not load?

I widened the window to 5994x1890 spanning 5 monitors, and it still loaded.

**Comment by Kaldaien** [comment]
I am seeing some confusion in this thread. The issue is not the resolution of the window or output display itself, but of the image file.

3840x1600 isn't wider than 4096. Greater than 4096 in my testing is the point at which the source file is reported as corrupted when trying to open.

**Comment by Sawtaytoes** [comment]
That file I loaded is the one from the ZIP at the top that the guy was saying didn't load.

**Comment by Filoppi** [comment]
Fixed by latest commits.
